### ISSUE TITLE
Unable to create channel by specifying the members id's.

### ISSUE THREAD

**Issue by zeeshansuleman** [GetStream/stream-chat-swiftui#159] opened 2022-08-03 11:37 UTC
## What did you do?
I am trying to create a channel using createchannel method of stream SDK.

## What did you expect to happen?
I am expecting the channel will be created.

## What happened instead?
But I get below error.
```
{
  "code" : 17,
  "message" : "GetOrCreateChannel failed with error: \"User 'c70c4c05-1a9d-48c3-a97d-a0f1ba02c554' with roles ['user', 'channel_member'] is not allowed to perform action RecreateChannel in scope 'messaging'\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "StatusCode" : 403,
  "duration" : "0.00ms"
})
```

I am using below line of code to create a channel.
```
channelController = try? chatClient.channelController(createDirectMessageChannelWith: [skillrId, seekrId], type: .messaging, isCurrentUserMember: true, name: receiverName, extraData: [:])
            channelController?.synchronize { [weak self] (err) in
                //            self?.channelId = channelController?.channel?.cid
                if let error = err {
                    self?.isConnectionFailed = true
                    self?.errorString = String(localized: "Chat.Error.ChannelCreation")
                    logger.error("There is an error: \(error)", category: .userContext)
                    return
                }
                self?.navigateToChat = true
            }
```

## GetStream Environment
**GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
**iOS version:15
**Swift version: swift ui
**Device:iphone

**Comment by martinmitrevski** [comment] 2022-08-03 14:55
Hey @zeeshansuleman,

The error says 
```swift
"User 'c70c4c05-1a9d-48c3-a97d-a0f1ba02c554' with roles ['user', 'channel_member'] is not allowed to perform action RecreateChannel in scope 'messaging"
```
Therefore, you need to elevate the permissions for your users to a bigger role in your dashboard, in order for them to be able to re-create channels. You can find more details about this topic here:
https://getstream.io/chat/docs/ios-swift/legacy_permissions/?language=swift&q=adm#user-roles

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-08-03 15:37
If it works only the first time, it's actually expected. There's a difference between creating a channel and re-creating a channel. For the first one, you can do it with regular permissions, and for re-creating a channel, you need elevated ones. Alternatively, you can check if the channel is already created to avoid re-creation.

**Comment by zeeshansuleman** [comment] 2022-08-03 16:16
@martinmitrevski how can i check that if its created with specified members?

**Comment by zeeshansuleman** [comment] 2022-08-03 16:17
@martinmitrevski Also some time I get this one, which is related to the connectionId.

`[io.getStream.chat.core.web_socket_engine_queue] [APIClient.swift:188] [executeRequest(endpoint:completion:)] > Error MissingConnectionId in /Users/snx/Library/Developer/Xcode/DerivedData/Skillr-gdvokzcvjqdcveawwbaakhjoinef/SourcePackages/checkouts/stream-chat-swift/Sources/StreamChat/APIClient/RequestEncoder.swift:194 -> Failed to get `connectionId`, request can't be created.`

**Comment by martinmitrevski** [comment] 2022-08-03 16:30
@zeeshansuleman you can persist the channel id after it's created the first time and save it in your backend. Then, you can use `channelController(for cid: ChannelId)` instead.

The other error means your connection dropped, probably you've lost connection for a moment. However, it's automatically restored, this is just logged.

**Comment by zeeshansuleman** [comment] 2022-08-03 16:45
@martinmitrevski we are not involving the BE to store those cid, I thought there would be a method in sdk to get the status of channel by passing the members id. For the other issue, I am getting this issue again an again.

**Comment by zeeshansuleman** [comment] 2022-08-03 17:32
@martinmitrevski Regarding setting the permission, Why would a conversation between two users who are authorized to chat with each other need a moderator?

**Comment by martinmitrevski** [comment] 2022-08-03 21:05
@zeeshansuleman about the permission - the reason is that with the method you are using, you are re-creating the channel. If it's only creation, the permissions are normal. As mentioned above, the way to avoid this is to store the channel id on your backend. If that's not an option, you would need to elevate the permissions of the users.

**Comment by zeeshansuleman** [comment] 2022-08-03 21:28
@martinmitrevski can you guide me about elevating the permissions? which permissions set should be given to the members of channels?

**Comment by martinmitrevski** [comment] 2022-08-04 05:55
@zeeshansuleman in your dashboard, go to Channel Types, select messaging. At the bottom, you can edit the permissions, see screenshot:
<img width="1658" alt="Screenshot 2022-08-04 at 07 50 47" src="https://user-images.githubusercontent.com/2971717/182773131-2ba21352-0af0-42ac-b98f-badd50dc525d.png">
You need to move the `RecreateChannel` permission to your regular users (by default it's for admin).

If you still have trouble setting this up, I would suggest to reach out to our support, they will help you.

**Comment by zeeshansuleman** [comment] 2022-08-04 20:01
@martinmitrevski i was able to resolve the issue by changing the way of channel creation. I have observed another issue that I need to connect my user each time the app launches, If I do not connect I get missing auth error. I believe the SDK gets connected single time on login but for me it does not work even though my token expiry time is 8 hour.

**Comment by zeeshansuleman** [comment] 2022-08-04 22:47
@martinmitrevski Now I have changed the way channels are being created, I am creating the channel by specifying the channel id like below, and as per the SDK doc using this method will return the channel if already created but still I am getting the same issue.

```
let ids = (skillrId+seekrId).replacingOccurrences(of: "-", with: "")
        let sortedString = String(ids.sorted())        
        let channelId = ChannelId(type: .messaging, id: sortedString)
        /// 2: Use the `ChatClient` to create a `ChatChannelController` with the `ChannelId`.
        channelController = try? chatClient.channelController(createChannelWithId: channelId,name: receiverName)

        /// 3: Call `ChatChannelController.synchronize` to create the channel.
        channelController?.synchronize { error in
            if let error = error {
                /// 4: Handle possible errors
                logger.error("There is an error in creating channel: \(error)", category: .userContext)
                onComplete("Channel creation failed with error: \(error.localizedDescription)")
                return
            }
            onComplete(nil)
        }
```

**Comment by martinmitrevski** [comment] 2022-08-05 07:42
hey @zeeshansuleman,

The code you've listed here will work correctly, only if you are not deleting the channels in the meantime. For example, we are doing the same thing in our Demo app and it works as expected. See here: https://github.com/GetStream/stream-chat-swiftui/blob/main/DemoAppSwiftUI/NewChatViewModel.swift. (from line 131)

If this doesn't work with the error that the channel can't be **recreated**, then this means you've deleted the channel and want to create it again. In that case, you need to set the correct permissions (RecreateChannel) in the dashboard, as I've added an example above.

**Comment by zeeshansuleman** [comment] 2022-08-05 10:06
@martinmitrevski I am sure that we are not deleting the channel, If possible I can show you the updated code again in a call?

**Comment by martinmitrevski** [comment] 2022-08-05 13:25
@zeeshansuleman I would suggest to check again the sample code I've linked above and when the error appears check on the dashboard if the channel is really there. The method from the SDK should work as expected, since it's already used by a lot of customers.

If the issue still persists, it's best to create a support ticket. Our support team will help you in figuring out what's the issue, since this is not really a problem in the SwiftUI SDK.

Best,
Martin

**Comment by zeeshansuleman** [comment] 2022-08-05 21:41
@martinmitrevski sure. I will create a support ticket. In SwiftUI stream SDK do we have any callback to detect that the token is expired, as I am also frequently getting auth error 401, Even though the token is valid. Look like the websocket is getting disconnected.

**Comment by martinmitrevski** [comment] 2022-08-08 07:35
@zeeshansuleman did you pass a token provider in the `connectUser` method? The token provider closure is called whenever the token is expired, so you need to provide a mechanism for refreshing the token. For more details, please check our docs here, especially the last code snippet: https://getstream.io/chat/docs/ios-swift/tokens_and_authentication/?language=swift#how-to-refresh-expired-tokens.

**Comment by zeeshansuleman** [comment] 2022-08-08 18:28
@martinmitrevski I confirmed from my BE, and as per them, the token expiration time is 8 hours. But on the app side when I connect with that token I need to connect on each app launch otherwise I am getting unauthication errors. Can it be related to the stream socket ? It looks like it's getting disconnected once the app goes background.

**Comment by zeeshansuleman** [comment] 2022-08-08 19:56
@martinmitrevski thanks for the insight of token provider I will check that out. Regarding the previous error which is related to the  "['user', 'channel_member'] is not allowed to perform action RecreateChannel in scope 'messaging" .
I have a finding and find out the use case for this. This error appears when I initiate a chat with a person and then after sending one or two message I delete the channel, Now if I try to initiate the chat again I get this error. What am I doing wrong here. to delete the channel I am using this code.

```
channelController = chatClient.channelController(for: .init(type: .messaging, id: channelID))

        channelController?.deleteChannel { error in
            if let error = error {
                onComplete("Channel deletion failed with error: \(error.localizedDescription)")
                return
            }
            onComplete(nil)
        }
```


Also with this deleted chat I am not able to do chat again forever.

**Comment by martinmitrevski** [comment] 2022-08-09 07:23
@zeeshansuleman why exactly do you need to delete a channel, what's your use-case? In general, this function should be used only if the user takes a delete action by themselves. Therefore, it's expected behaviour that you can't chat in a deleted channel unless you re-create it with the permissions I've described above.

About the auth issue - if your app was killed, you anyway need to connect the user on app start. While the app is used, if a token expires, the token provider will be called and you get the chance to refresh the token. The WS connection is kept alive for few minutes in the background, if you have set `staysConnectedInBackground` in the `ChatClientConfig` to true (which is by default). It reconnects automatically when coming from background to foreground, if `shouldConnectAutomatically` in the same config is true (also default value). Please check if you modified these values and that you call connectUser on every fresh app start. The demo app can also help as an example.

**Comment by zeeshansuleman** [comment] 2022-08-09 08:24
@martinmitrevski The user who created this channel is trying to delete himself. Which is an obvious use case like other messaging platforms. I am trying to delete a conversation from the chat listing by swipe the cell. We have a use case that user can delete his conversation later on. The other point regarding configuration changes, i have not done any modification in it. If connection on each app launch is required then i will do like that.

**Comment by martinmitrevski** [comment] 2022-08-09 15:42
@zeeshansuleman When a channel is deleted, it has to be re-created in order to be usable again. If you want to allow re-creation of channels after they are deleted from users, then setting the permission I've shared above (RecreateChannels) will work for your use-case.

About the token, If it doesn't expire, yes, you can do that - we have the same setup in our demo app. If it expires, you can use the `tokenProvider` version of the `connectUser` and provide a closure that will load the token from your backend in case it expires.
That's this method:
```swift
    public func connectUser(
        userInfo: UserInfo,
        tokenProvider: @escaping TokenProvider,
        completion: ((Error?) -> Void)? = nil
    )
```

**Comment by martinmitrevski** [comment] 2022-08-11 09:22
Closing this issue. If you have additional questions, feel free to reach our support team.

**Closed by martinmitrevski** 2022-08-11 09:22 UTC
