### ISSUE TITLE
I am having issues in showing image in the chat for the receiver user and for the channel

### ISSUE THREAD

**Issue by zeeshansuleman** [GetStream/stream-chat-swiftui#174] opened 2022-08-12 19:41 UTC
## What did you do?
I connected the stream by providing my avatar URL, but when i try to have a chat with other member i don't see his image in the chat. Neither in chat list view nor in one-one chat.

## What did you expect to happen?
The receiver image be shown to sender and vice versa.

## What happened instead?
I found a nil image but get the name of the receiver.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context

here is the code which returns me name but no image. Its the default SDK function.

```
func getReceiverNameImageUrl(){
        let controller = chatClient.memberListController(query: .init(cid: channel.cid))
        controller.synchronize() { error in
            if error == nil{
                let receiver = controller.members.filter({$0.name != currentUserName}).first
                if let receiverName = receiver?.name{
                    self.receiverName = receiverName
                }
                if let receiverImageUrl = receiver?.imageURL?.description{
                    self.receiverImageUrl = receiverImageUrl
                }
            }
        }
    }
```

and to connect members i have used this piece of code.

 ```
chatClient.connectUser(
            userInfo: .init(id: userAuthenticationManager?.userDetails?.id ?? "",
                            name: userAuthenticationManager?.userDetails?.displayName ?? "",
                            imageURL: URL(string: imageString)!),
            token: token
        ) { error in
            if let error = error {
                log.error("failed to connect the user with stream \(error)")
            } else {
                log.error("user connected with the stream sdk")
            }
        }
```

and to create a channel I use this piece of code.
```
channelController = try? chatClient.channelController(createDirectMessageChannelWith: [skillrId,seekrId], name: receiverName, extraData: [:])
        
        /// 3: Call `ChatChannelController.synchronize` to create the channel.
        channelController?.synchronize { error in
            if let error = error {
                /// 4: Handle possible errors
                logger.error("There is an error in creating channel: \(error)", category: .userContext)
                onComplete("Channel creation failed with error: \(error.localizedDescription)")
                return
            }
            onComplete(nil)
        }
```

**Comment by martinmitrevski** [comment] 2022-08-15 08:45
Hey @zeeshansuleman,

Can you print out an example of one such URL?  I see two options here:
- either it's nil, in which case there might be an issue with the way you send the image url
- it has value, but the image needs additional authorization (it's not public), which means you would need to provide your own CDN implementation.

Looking forward to your feedback.

**Comment by zeeshansuleman** [comment] 2022-08-15 11:01
@martinmitrevski In my case it is always nil, Although during connecting the users with stream SDK i am passing imageURL param in the connect call as below.

```
// default image in case of users who are not skillrs, As seekrs don't have image.
        var imageString = "https://i.imgur.com/X1H8yo3_d.png"
        
        // if user is skillr send his profile image
        if userAuthenticationManager?.isUserSkillr ?? false {
            imageString = userAuthenticationManager?.skillrDetails?.profileImage ?? imageString
        }
        chatClient.connectUser(
            userInfo: .init(id: userAuthenticationManager?.userDetails?.id ?? "",
                            name: userAuthenticationManager?.userDetails?.displayName ?? "",
                            imageURL: URL(string: imageString)!),
            token: token
        ) { error in
            if let error = error {
                log.error("failed to connect the user with stream \(error)")
            } else {
                log.error("user connected with the stream sdk")
            }
        }
```

you can see i am passing imageString in connection call.

**Comment by martinmitrevski** [comment] 2022-08-15 14:03
@zeeshansuleman can you extract the `userInfo` part in a variable and print it before you call the connectUser method? It might be that the id is empty the first time you call this? 

If that doesn't help, you can send us a minimal reproducible sample project with the issue, and we can have a look.

**Comment by zeeshansuleman** [comment] 2022-08-15 15:16
@martinmitrevski I print the UserInfo when first time connectUser method called.
```▿ UserInfo
  - id : "75bdc17e-4faa-4122-bb8c-642e03604800"
  ▿ name : Optional<String>
    - some : "Honyyy Albela"
  ▿ imageURL : Optional<URL>
    ▿ some : https://skillr-uploads-development.s3.amazonaws.com/images/skillrImages/75bdc17e-4faa-4122-bb8c-642e03604800_profileImage_ImageFile2022-08-05%2015%3A40%3A18%20%2B0000.jpg
      - _url : https://skillr-uploads-development.s3.amazonaws.com/images/skillrImages/75bdc17e-4faa-4122-bb8c-642e03604800_profileImage_ImageFile2022-08-05%2015%3A40%3A18%20%2B0000.jpg
  - extraData : 0 elements```
We are getting the user 'id' and also 'imageUrl'.

**Comment by zeeshansuleman** [comment] 2022-08-15 15:36
@martinmitrevski As you can see i am passing the image URL, but on the other end the receiver does not see this image from the below method i get nil always.

```
func getReceiverNameImageUrl(){
        let controller = chatClient.memberListController(query: .init(cid: channel.cid))
        controller.synchronize() { error in
            if error == nil{
                let receiver = controller.members.filter({$0.name != currentUserName}).first
                if let receiverName = receiver?.name{
                    self.receiverName = receiverName
                }
                if let receiverImageUrl = receiver?.imageURL?.description{
                    self.receiverImageUrl = receiverImageUrl
                }
            }
        }
    }

```

**Comment by martinmitrevski** [comment] 2022-08-15 18:01
Hey @zeeshansuleman,

Here are two suggestions: 
- instead of `imageURL?.description`, you should use `imageURL?.absoluteString`.
- if that doesn't work, maybe you can try getting the members directly from the channel with sth like:
```swift
channel.lastActiveMembers
            .filter { $0.id != chatClient.currentUserId }
```
If that doesn't work, please send us a sample project where you reproduce this issue, and we will take a look.

**Comment by zeeshansuleman** [comment] 2022-08-16 14:32
@martinmitrevski using filter approach you suggested i was able to see the image only once. Trying this the second time it shows nil as well.

**Comment by martinmitrevski** [comment] 2022-08-17 07:24
@zeeshansuleman is the active member the same one as the one that has shown the image? Can you compare those two values? This seems like some invalid state in your app - something that causes re-draw and looses your state. The imageURL works reliably in the SDK this way - so far we haven't had reports from customers.

I think it's most efficient if you send us a sample project that reproduces your issue, and we can help troubleshooting.

**Comment by martinmitrevski** [comment] 2022-08-17 14:38
hey @zeeshansuleman, 
We also have an example where we fetch images directly from the channels - you can find it here: https://github.com/GetStream/stream-chat-swiftui/blob/9a83c3fd3ed7ef83ba08537826c869716c61227b/Sources/StreamChatSwiftUI/ChatChannelList/ChannelHeaderLoader.swift#L55.

About a sample project, you can just skip the auth token mechanism, and just hardcode one token where the issue is reproducible.

**Comment by zeeshansuleman** [comment] 2022-08-18 19:18
@martinmitrevski I have created this demo where that issue is reproduced. Have a look into this. Thanks.

[StreamChatDemo.zip](https://github.com/GetStream/stream-chat-swiftui/files/9376899/StreamChatDemo.zip)

**Comment by martinmitrevski** [comment] 2022-08-19 08:12
Hey @zeeshansuleman, 

Thanks for the demo project. I've had a look at it, and I have one question - have you at least once logged in with these users in the chat, using the `connectUser` method and passing the correct image URL as a parameter? You need to login at least once, so that the chat knows about the image URL.

Code wise, there's nothing wrong. I've picked one user from our demo app and used it for testing in your project, and all the images are loaded instantly. It seems the issue is that you're creating the channels programatically, but you haven't initially connected the users.

**Comment by zeeshansuleman** [comment] 2022-08-19 09:19
> Hey @zeeshansuleman, 
> 
> Thanks for the demo project. I've had a look at it, and I have one question - have you at least once logged in with these users in the chat, using the `connectUser` method and passing the correct image URL as a parameter? You need to login at least once, so that the chat knows about the image URL.
> 
> Code wise, there's nothing wrong. I've picked one user from our demo app and used it for testing in your project, and all the images are loaded instantly. It seems the issue is that you're creating the channels programatically, but you haven't initially connected the users.

Yes, i have connected the users both sender and receiver before creating the channel.

**Comment by martinmitrevski** [comment] 2022-08-19 09:49
@zeeshansuleman can you please verify this by going to your dashboard, select Explorer -> users -> (find a concrete user), and check if the `image` field has the correct value (see screenshot).
![Screenshot 2022-08-19 at 11 46 51](https://user-images.githubusercontent.com/2971717/185593088-7d32962b-0a1c-4900-b7f8-7bcf2b5d5366.png)

**Comment by martinmitrevski** [comment] 2022-08-23 16:09
@zeeshansuleman do you still have issues with this one or we can close it?

**Comment by martinmitrevski** [comment] 2022-08-27 06:18
Closing because of inactivity. Feel free to re-open it if the issue happens again.

**Closed by martinmitrevski** 2022-08-27 06:18 UTC
