### ISSUE TITLE
`highPriorityGesture` on `LazyLoadingImage` is swallowing tap events

### ISSUE THREAD

**Issue by ktreangen-at-ramsey** [GetStream/stream-chat-swiftui#672] opened 2024-12-02 19:36 UTC
## What did you do?

I tried to add an `onTapGesture` to the default `makeImageAttachmentView` so that I could report analytics about user image usage.

## What did you expect to happen?

`onTapGesture` handler would be called

## What happened instead?

`highPriorityGesture` is swallowing the on tap event and preventing detection. 

## GetStream Environment
**GetStream Chat version:** 4.66.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** iOS 18
**Swift version:** 5
**Xcode version:** 16.1
**Device:** Any

## Additional context

https://github.com/GetStream/stream-chat-swiftui/blob/c414e88e682b5dcb762532053496b9326cbfe9d8/Sources/StreamChatSwiftUI/ChatChannel/MessageList/ImageAttachmentView.swift#L364

**Comment by nuno-vieira** [comment] 2024-12-03 00:43
Hi @ktreangen-at-ramsey,

This is a known issue, and it is already fixed in development. It will come on this week's release. 

Best,
Nuno

**Comment by nuno-vieira** [comment] 2024-12-03 00:43
Duplicate of https://github.com/GetStream/stream-chat-swiftui/issues/670

**Closed by nuno-vieira** 2024-12-03 00:43 UTC

**Comment by laevandus** [comment] 2024-12-06 10:20
@ktreangen-at-ramsey 4.68.0 has been released, please upgrade.
