### ISSUE TITLE
Keyboard disappears on push

### ISSUE THREAD

**Issue by saidReclip** [GetStream/stream-chat-swiftui#201] opened 2022-09-14 17:58 UTC
## What did you do?
Go to a thread. Activate keyboard. Go to the settings while keyboard is shown. Go back.

## What did you expect to happen?
You expect keyboard and composer to be visible.

## What happened instead?
Keyboard disappeared. Composer is active.

This bug reproduces on the demo app. 
![IMG_0716](https://user-images.githubusercontent.com/102264702/190227802-96ebbaec-fe99-406e-8b25-7fbd09d30afc.png)

@martinmitrevski this issue is a release blocker for Reclip. @jfru

**Comment by martinmitrevski** [comment] 2022-09-14 18:20
Hey @saidReclip,

Thanks for reporting this. We're looking into it with high priority.

As soon as we have an update, we will let you know.

**Comment by martinmitrevski** [comment] 2022-09-14 18:59
Hey @saidReclip,

We have fixed the issue, and it's available on the `keyboard-push-fix` branch. We would like to test it a bit more before we merge it in `main` (most likely tomorrow).

If you have some time, please provide feedback if it solves the issue for you.

Best,
Martin

**Comment by saidReclip** [comment] 2022-09-14 19:59
Hey @martinmitrevski , 
Thanks for such a fast feedback. 
I just checked it on our app and seems like it is not working as expected. 
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-09-14 at 22 54 32](https://user-images.githubusercontent.com/102264702/190250486-ee386a30-8f3a-4d6c-9175-59c9b6caf38f.gif)

Best, Said

**Comment by martinmitrevski** [comment] 2022-09-14 20:20
Thanks for testing @saidReclip, we will look into this case further.

**Comment by martinmitrevski** [comment] 2022-09-15 15:50
@jfru I'm still looking into this. I'm trying to find a way to control this from our SDK, but it's challenging since the screen is outside of our SDK, in your app and you're also using a custom swipe gesture. 
I'm still trying some things, but I will soon share alternatives if this is not possible.

**Comment by martinmitrevski** [comment] 2022-09-15 17:11
hey @saidReclip, can you please update the branch and test again? Now it should be better.

Note: if you're not using our default `ChatChannelInfoViewModel`, you will need to do some adjustments in your screen's handling. Let me know if that's the case.

**Comment by AndrewSB** [comment] 2022-09-15 19:40
Hey @martinmitrevski, we just tested the updated branch, it doesn't seem to solve the problem. 

we also tried it from inside your demo app, and this is what we saw

![Simulator Screen Recording - iPhone 13 Pro Max - 2022-09-15 at 20 16 28](https://user-images.githubusercontent.com/3814772/190493980-7c4740c4-af93-4f03-b31b-3ac98711f43c.gif)

it exhibits the same problem that we see in our app

**Comment by AndrewSB** [comment] 2022-09-15 19:51
and just to be clear - this is on iOS 16

**Comment by martinmitrevski** [comment] 2022-09-15 19:56
Hey @AndrewSB,

This is the maximum that we could do with the keyboard being displayed. It is not possible to keep the keyboard opened in the chat view while you're in swiping back in other screens (at least I couldn't find a way - if you have any ideas I'm open to suggestions).

The other approach would be to collapse the view inside the SDK. In that case, you can check the state in your custom gesture and call becomeFirstResponder when the gesture finishes.

Let me know your thoughts.

**Comment by AndrewSB** [comment] 2022-09-15 20:32
> The other approach would be to collapse the view inside the SDK. In that case, you can check the state in your custom gesture and call becomeFirstResponder when the gesture finishes.

yeah we'll probably do this. i'll look into if there's another way to keep the keyboard opened, but i know if you've looked you're probably right

**Comment by martinmitrevski** [comment] 2022-09-16 08:27
@AndrewSB, @saidReclip This is actually iOS 16 only issue. It's even reproducible with this chunk of code on an empty project:
```swift
struct ContentView: View {
    
    @State var text = ""
    
    var body: some View {
        NavigationView {
            VStack {
                Spacer()
                NavigationLink {
                    Text("test")
                } label: {
                    Text("Tap me")
                }
                TextField("", text: $text)
            }
            .padding()
        }
    }
}
```
Looking into this.

**Comment by martinmitrevski** [comment] 2022-09-16 09:06
I've also created a SO question for this: https://stackoverflow.com/questions/73742103/ios-16-keyboard-safe-area-not-updated-on-push.

**Comment by martinmitrevski** [comment] 2022-09-16 15:54
We've fixed this in the SDK's chat header by calling `resignFirstResponder` before pushing the chat info screen. Similar fix should work for your screen too. Additionally, you can try showing it back by using your custom swipe gesture, as discussed before.

**Comment by AndrewSB** [comment] 2022-09-16 16:42
gotta love the new OS SwiftUI bugs

thanks @martinmitrevski, @saidReclip will give that a shot and we'll close this out if that works 😄

**Comment by martinmitrevski** [comment] 2022-09-22 21:52
@saidReclip, I guess we can close this one. Feel free to reopen it if there's some update needed from SDK's side.

**Closed by martinmitrevski** 2022-09-22 21:52 UTC

**Comment by saidReclip** [comment] 2022-09-22 21:53
@martinmitrevski yes, thank you so much. This one is okay now.
