### ISSUE TITLE
Message not coming for second user

### ISSUE THREAD

**Issue by negna1** [GetStream/stream-chat-swiftui#193] opened 2022-09-06 15:43 UTC
## What did you do?
In main branch there is bug, Chat sending messages not updating and not sending, Can you check that?
I upload repo after bottom typing indicator and since than I detect that from second user message not comes

## What did you expect to happen?
to send message

## What happened instead?
not senf

## GetStream Environment

https://user-images.githubusercontent.com/48616435/188677581-c055eecc-70fe-41ac-a26b-e8646642bed3.mov

**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment] 2022-09-06 15:54
Hey @negna1,

I've just tested on our `main` branch and this functionality works correctly. 

Can you please provide more details how this has happened? Is this always reproducible or it happens from time to time? Is there any custom logic around the filtering of the messages? Also, some logs from Xcode would be helpful.

Another thing I've noticed is that the chat apps are different in the different simulators. Might be good to test with the same states (e.g. you might have applied different filters to the messages).

Looking forward to your feedback.

**Comment by negna1** [comment] 2022-09-07 14:24
It is always hapenning , I am testing with same branch and it is not coming for another user, but it is saved in simulator after quit :/ maybe it is problem from your side because I am sure it was working

**Comment by negna1** [comment] 2022-09-07 14:53
When I am using old chat (stream chat UI) and write to swiftui chat message comes but swiftui chat messages not receiving (but in swiftui chat it seems that it sent)

**Comment by negna1** [comment] 2022-09-07 14:54
so I think there is not any channel id problem , becuase than it can't received than

**Comment by martinmitrevski** [comment] 2022-09-07 15:05
Hey @negna1, 

thanks for the update. Can you reproduce this issue in our demo app? 

If not, can you share with us a minimal reproducible project with the issue at [martin.mitrevski@getstream.io](mailto:martin.mitrevski@getstream.io), so we can take a look?

**Comment by martinmitrevski** [comment] 2022-09-15 20:47
Closing this since we haven't received feedback. Feel free to reopen it and share a minimal reproducible project if you still have the issue.

**Closed by martinmitrevski** 2022-09-15 20:47 UTC
