### ISSUE TITLE
App crashes when selecting multiple images to send

### ISSUE THREAD

**Issue by dipeshpatel7733-hub** [GetStream/stream-chat-swiftui#238] opened 2022-11-29 06:59 UTC
## What did you do?
Have selected a channel and tried to send more than 4 images to send and Issue is only happening when quickly clicking on the send button before images are loaded it got crashed

## What did you expect to happen?
I expect to send more than 4 images at once

## What happened instead?
Navigated to a channel and selected more than 4 images and tried sending them and app got crashed, it is happening for iOS 14 devices but it is working for iOS 15

Have downloaded your demo app and tried running the same use case by selecting more than 4 images to send and Issue is only happening when quickly clicking on the send button before images are loaded it got crashed at below file, am attaching the screen shot, please take a look.

![Screenshot 2022-11-29 at 12 27 50 PM](https://user-images.githubusercontent.com/85125016/204460452-35557134-c995-48a4-abc7-0d0bc30aef61.png)

## GetStream Environment
**GetStream Chat version:** 4.24.1
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 14.4
**Xcode version:**  13.4.1
**Device:** iPhone SE 2nd generation (iOS 14.4)

**Comment by martinmitrevski** [comment] 2022-11-29 08:50
Hey @dipeshpatel7733-hub,

Thanks for reporting this. I was able to reproduce it on an older iOS 14 device. 

We will look into it, and get back to you when we have an update.

Best,
Martin

**Comment by dipeshpatel7733-hub** [comment] 2022-12-01 12:02
Hey @martinmitrevski any update on this issue?

**Comment by martinmitrevski** [comment] 2022-12-02 11:53
Hey @dipeshpatel7733-hub, the issue is now fixed and available on `main`.
Thanks again for reporting.

**Closed by martinmitrevski** 2022-12-02 11:53 UTC
