### ISSUE TITLE
Chat not shows when disconnect current user and re-connect with another user

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swiftui#314] opened 2023-05-17 18:08 UTC
## What did you do?
I am trying to implement the Multiple Profile feature into the IOS app. First I login with the single account and our chat works fine, but when I login with second account and disconnect the previous user with StreamChatSDK and connect second user with the StreamChatSDK then sometimes chat not shows and sometimes wrong Chat shows. Like you could see the screenshot.

As you can see I chat not shows, user successfully connected with StreamChatSDK but chat not shows.
<img width="369" alt="Screenshot 2023-05-17 at 12 50 38 PM" src="https://github.com/GetStream/stream-chat-swiftui/assets/127435927/f0bc1bcc-8f30-41da-ab32-e571b15ca396">

In this screenshot you could see the wrong chat shows, it lookes like some search chat shows instead of Channels list.
<img width="366" alt="Screenshot 2023-05-17 at 12 53 59 PM" src="https://github.com/GetStream/stream-chat-swiftui/assets/127435927/22dd5ccb-6ba9-440e-8022-119bd0e7c152">

When I switch the profile, I disconnect the current connected user with StreamChatSDK and then re-connect new user with it, but no channel shows in channels list. As you can see in the video. 
https://github.com/GetStream/stream-chat-swiftui/assets/127435927/afaadefb-9a0d-434d-9967-ea5b02ec86f5

But when I re-run the app then could see the actual channel list. As you can see the screenshot.
<img width="364" alt="Screenshot 2023-05-17 at 12 57 44 PM" src="https://github.com/GetStream/stream-chat-swiftui/assets/127435927/0a2ec19a-7f66-48f8-9b70-96caa881db1d">

### Connect with Chat Code
```swift
func connectUser(onComplete: (()->())? = nil) {
        chatClient.connectUser(
            userInfo: .init(
                id: userAuthanticationManager.supportUserId!,
                name: userAuthanticationManager.username),
            token: try! Token(rawValue: userAuthanticationManager.supportToken!)
        ) { error in
            if let error = error {
                print("failed to connect the user with stream \(error)")
            } else {
                logger.info("user connected with the stream sdk", category: .chat)
                self.registerForPushNotifications()
            }
            onComplete?()
        }
    }
```

### Switch User Method
First calling the disconnect function and then re-connect the user with StreamChatSDK. User connect successfully again with StreamChatSDK but chat not shows.
```swift
func switchUser(profile: ProfileItem){
        chatClient.disconnect { }
        userAuthanticationManager.setUserLoggedInWith(
            id: "",
            jwt: profile.jwt ?? "",
            username: profile.username ?? "",
            supportToken: profile.supportToken ?? "",
            supportUserId: profile.supportUserId ?? "",
            isSaveInCoreData: false)
        ChatManager.shared.connectUser {}
    }
```

## What did you expect to happen?
Chat not showing.

## What happened instead?
Chat should show when current user disconnect and then new user again connect with StreamChatSDK.

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** IOS 15
**Swift version:** Swift 5+
**Xcode version:** 14.3
**Device:** Simulator IPhone 14 Pro

**Comment by martinmitrevski** [comment] 2023-05-18 06:32
Hi @Zee-93,

There are several issues with your `switchUser` method:
- you are calling `disconnect`, but you should call `logout`
- you are not waiting for the completion handler on the `disconnect` and `connect`, which can lead to inconsistencies
- If you see some old data, that means you must store some old token in your app. Make sure that you clear any additional state you use in your app when you switch the user.
- Additionally, be careful about the state of your SwiftUI views, you would need to re-create them, together with the view models, since they would depend on a different user now.

Closing this since it's not a bug in the SDK, but an integration issue on your side. If you still have issues, please reach out to our support.

**Closed by martinmitrevski** 2023-05-18 06:32 UTC
