### ISSUE TITLE
In ChatChannelView, keyboard doesn't come up when the scroll view is bouncing at the bottom

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#33] opened 2022-02-12 06:19 UTC
https://user-images.githubusercontent.com/97132583/153699604-e8189bcc-da0b-42be-93c7-2fbc53e6efe6.mp4

## What did you do?
In the ChatChannelView, scroll pretty hard and fling toward the bottom. The scroll will do a spring bounce (so far so good).
While the spring bounce is happening, tap on the TextField input ... notice that the keyboard attempts to come up but quickly gets dismissed.

This is a pretty common interaction: I come into the app to check a batch of messages I missed; I scroll up to see them, then I scroll down and fling hard ==> then I tap on the TextField input view to write a response. Keyboard fails to come up.

This bug doesn't exist in any other messaging apps like iMessages, Whatsapp or Signal.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 pro

**Comment by martinmitrevski** [comment] 2022-02-14 07:21
Hi @linhewinner, 

Thanks for reporting this. We will analyse the issue internally and provide a fix soon.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-02-14 13:15
@linhewinner, the issue is fixed and available on the `main` branch. It will be released on Wednesday.

Thanks again for providing such useful input towards improving our SDK 👍

**Closed by martinmitrevski** 2022-02-14 13:15 UTC
