### ISSUE TITLE
Issue with message ordering

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#156] opened 2022-08-01 12:12 UTC
## What did you do?
- create a new message with attachments
- quickly create a new message just after first message
- Wait for first message to upload its all attachments
- The second message shows before first message (sorting order changed)

## What did you expect to happen?
- The sorting order should not change

## GetStream Environment
**GetStream Chat version:** 4.19.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context

https://user-images.githubusercontent.com/47667077/182144905-e0bdfb68-6d98-45cf-b3c3-d14dd35450c6.mp4

**Comment by martinmitrevski** [comment] 2022-08-01 12:33
Hello @ajay-simform,

This is the expected behaviour in this case - the message is not sent until all attachments are uploaded (which is the behaviour that most chat apps have).

Therefore, I'm closing this, since we don't plan to change this behaviour.

Best,
Martin

**Closed by martinmitrevski** 2022-08-01 12:33 UTC

**Comment by martinmitrevski** [comment] 2022-08-01 12:49
Hey @ajay-simform, 

The upload state of an attachment can be found in `ChatMessageAttachment`'s `uploadingState` property. You can see an example how it is used in our `withUploadingStateIndicator`.

However, I'm not sure if that will help you. We don't support any custom ordering of messages (we only support newest to oldest and vice versa).
