### ISSUE TITLE
Broken messages layout for iPad Slide Over mode

### ISSUE THREAD

**Issue by angelinaFri** [GetStream/stream-chat-swiftui#271] opened 2023-02-07 10:18 UTC
## What did you do?
Run app on iPad in Slide Over mode

## What did you expect to happen?
Messages layout to be updated accordingly

## What happened instead?
Messages width seem to be too thin and looks broken

## GetStream Environment
**GetStream Chat version:**
StreamChatUISwiftUI 4.24.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
StreamChatUI
**iOS version:**
16.2
**Device:**
All iPads

**Comment by nuno-vieira** [comment] 2023-02-07 11:41
Hi @angelinaFri,

Are you using SwiftUI? It is not clear in your GetStream Environment.

**Comment by angelinaFri** [comment] 2023-02-07 13:39
Yes, thank you for clarification!

**Comment by martinmitrevski** [comment] 2023-02-07 14:58
Hey @angelinaFri,

Thanks for reporting this. The issue is fixed and available on our `main` branch. It will be included in our next release.

Best,
Martin

**Closed by martinmitrevski** 2023-02-07 14:58 UTC
Labels: bug, swiftui-repo
