### ISSUE TITLE
Image Picker's tap target is way off

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#31] opened 2022-02-12 06:01 UTC
https://user-images.githubusercontent.com/97132583/153699219-b253c7e5-486e-44c0-a258-c55c48e38c7d.mp4

## What did you do?
When I tap at the bottom half of the Tiger photo, I ended up selecting the video below. See the attached video

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment] 2022-02-14 07:21
Hi @linhewinner, 

Thanks for reporting this. We will analyse the issue internally and provide a fix soon.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-02-14 09:59
The issue is fixed on `main` and it will be included in the next release on Wednesday.

**Closed by martinmitrevski** 2022-02-14 09:59 UTC
