### ISSUE TITLE
Scroll unresponsive in Chat message area

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#670] opened 2024-11-29 09:12 UTC
## What did you do?
Trying to scroll on chat while finger/cursor is on any message area.

## What did you expect to happen?
It should scroll the chat.

## What happened instead?
I doesn't scroll unless i place my finger outside the message area.

## GetStream Environment
**GetStream Chat version:** : 
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.5
**Swift version:** 5
**Xcode version:** 16.1
**Device:** Iphone 15 Simulator

## Additional context
This just started to happen as soon as I updated to version 4.67.0.
Can reproduce in the demo application.

https://github.com/user-attachments/assets/ee469855-e472-4522-8822-59c84ed01ac8

**Comment by nuno-vieira** [comment] 2024-11-29 14:18
Hi @fceldeiro

Thank you for the report! Indeed, I'm able to reproduce this on Testflight, but when compiling from Xcode, everything works fine 🤔 Looking at this [thread](https://forums.developer.apple.com/forums/thread/760035) it looks like it is a bug from Apple introduced on iOS 18 with highPriorityGestures 😞 

We will see if there is an alternative to fix this, if not, we will revert the change we did on 4.67.0. Expect this to be fixed in the next week 👍 

Best,
Nuno

**Comment by laevandus** [comment] 2024-12-04 07:08
Hi @fceldeiro, this issue is fixed in [4.68.0](https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.68.0). Thank you for reporting it.

**Closed by laevandus** 2024-12-04 07:08 UTC
Labels: bug, Upcoming
