### ISSUE TITLE
User Avatar Flashes on Reaction Click

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swiftui#176] opened 2022-08-17 14:50 UTC
## What did you do?
added and removed reactions

## What did you expect to happen?
User avatar shouldn't flashes while adding and removing reactions 

## What happened instead?
User Avatar Flashes on Reaction Click (Video attached)

## GetStream Environment
**GetStream Chat version: 4.20.0 ** 
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 15.5 **
**Swift version: 5 **
**Xcode version: 13.4.1**
**Device: iPhone-x **
## Additional context

https://user-images.githubusercontent.com/97155807/185168977-3579ea36-d701-4478-8599-1b18c7a797dc.mov

**Comment by martinmitrevski** [comment] 2022-08-17 15:55
Hey @jitendra-simform,

This is not reproducible in our Demo app. It seems you are doing some custom implementation around the reactions.

Maybe you can share some example code in order for us to help?

Best,
Martin

**Comment by jitendra-simform** [comment] 2022-08-18 03:31
> Hey @jitendra-simform,
> 
> This is not reproducible in our Demo app. It seems you are doing some custom implementation around the reactions.
> 
> Maybe you can share some example code in order for us to help?
> 
> Best, Martin

Sure @martinmitrevski , i will share patch file

**Comment by jitendra-simform** [comment] 2022-08-18 07:14
> Hey @jitendra-simform,
> 
> This is not reproducible in our Demo app. It seems you are doing some custom implementation around the reactions.
> 
> Maybe you can share some example code in order for us to help?
> 
> Best, Martin

Hello @martinmitrevski, Here is Patch file 
[CustomReactionViewPatch.diff.zip](https://github.com/GetStream/stream-chat-swiftui/files/9368451/CustomReactionViewPatch.diff.zip)

**Comment by martinmitrevski** [comment] 2022-08-18 14:30
Hey @jitendra-simform,

I've checked your patch, and it basically happens because you are refreshing the whole view with the reactions view model. You need to localize these updates to the reactions only. 

Here's an example how to do that:
```swift
class CustomReactionViewModel: ObservableObject, ChatMessageControllerDelegate {
    
    @Injected(\.chatClient) var chatClient
    
    @Published var reactions = [MessageReactionType]()
    
    var messageController: ChatMessageController?
    
    init(message: ChatMessage) {
        if messageController == nil {
            self.makeMessageController(for: message)
        }
        
        if let existing = messageController?.message {
            self.reactions = reactions(from: existing)
        } else {
            self.reactions = reactions(from: message)
        }
    }
    
    public func add(reaction: MessageReactionType) {
        messageController?.addReaction(reaction)
    }
    
    public func delete(reaction: MessageReactionType) {
        messageController?.deleteReaction(reaction)
    }
    
    private func makeMessageController(for message: ChatMessage) {
        if let channelId = message.cid {
            messageController = chatClient.messageController(
                cid: channelId,
                messageId: message.id
            )
            messageController?.synchronize()
            messageController?.delegate = self
        }
    }
    
    func messageController(
        _ controller: ChatMessageController,
        didChangeReactions reactions: [ChatMessageReaction]
    ) {
        guard let message = messageController?.message else { return }
        self.reactions = self.reactions(from: message)
    }
    
    func reactions(from message: ChatMessage) -> [MessageReactionType] {
        message.reactionScores.keys.filter { reactionType in
            (message.reactionScores[reactionType] ?? 0) > 0
        }
        .sorted(by: { lhs, rhs in
            lhs.rawValue < rhs.rawValue
        })
    }
    
}

struct CustomReactionView: View {
    
    @StateObject var viewModel: CustomReactionViewModel
    
    var message: ChatMessage
    
    // Init
    init(message: ChatMessage) {
        self.message = message
        _viewModel = StateObject(wrappedValue: CustomReactionViewModel(message: message))
    }

    var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack {
                ForEach(viewModel.reactions) { reaction in
                    CustomReactionViewContainer(message: message, reaction: reaction) { reaction in
                        reactionTapped(reaction)
                    }
                }
            }
        }
        .padding([.leading, .trailing])
        .padding(.bottom, 8)
        .padding(.top, message.isPartOfThread ? 8 : 0)
    }
    
    public func reactionTapped(_ reaction: MessageReactionType) {
        if userReactionIDs.contains(reaction) {
            viewModel.delete(reaction: reaction)
        } else {
            viewModel.add(reaction: reaction)
        }
    }
    
    private var userReactionIDs: Set<MessageReactionType> {
        Set(message.currentUserReactions.map(\.type))
    }

}
```

**Comment by martinmitrevski** [comment] 2022-08-23 16:09
@jitendra-simform any feedback on this one? can we close it?

**Comment by jitendra-simform** [comment] 2022-08-24 10:56
> @jitendra-simform any feedback on this one? can we close it?

Yes @martinmitrevski , Thank you so much for the update

**Closed** 2022-08-24 11:56 UTC
