### ISSUE TITLE
Unread indicator hangs around after entering a channel through a notification

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#146] opened 2022-07-21 22:53 UTC
https://user-images.githubusercontent.com/3814772/180320711-f41cccdd-0a85-4e5b-a644-575de6209c2e.MP4

## What did you do?

opened the app from a notification of a new message in a channel

## What did you expect to happen?

after backing out from the channel to the inbox, we expected the unread indicator to immediately disappear

## What happened instead?

the unread indicator on the channel list item stayed visible for a while longer. in the video, you can see if we navigate in from inside the app and back out of a channel, the unread indicator disappears immediately

**Comment by martinmitrevski** [comment] 2022-07-22 05:09
Hey @AndrewSB,

Thanks for the report. We've created an issue internally and we will analyze this. 

As soon as we have an update, we will report back.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-07-22 13:58
Hey @AndrewSB,

The issue is fixed now and available on `main`.

Best,
Martin

**Closed by martinmitrevski** 2022-07-22 13:58 UTC
