### ISSUE TITLE
The "X" button is invisible in Dark Mode

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#30] opened 2022-02-12 01:13 UTC
![258864273_267689202106332_4026149861756073656_n](https://user-images.githubusercontent.com/97132583/153690240-dc178122-8211-4af1-84a9-4e944ab4210d.png)
![272676579_492186735671682_1970805811181609195_n](https://user-images.githubusercontent.com/97132583/153690242-7f02693d-cafe-4ac8-9c86-c9167998bcfb.png)

See screenshots for comparison of Dark Mode vs Light Mode.
When I was in Dark mode, I actually thought there was no way to get out of this view ...

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment] 2022-02-14 08:20
Hi @linhewinner,

Thanks for reporting this. The issue is fixed now, and it's available on the `main` branch. 

It will be part of the 4.10.0 release on Wednesday.

Best, 
Martin

**Closed by martinmitrevski** 2022-02-14 08:20 UTC
