### ISSUE TITLE
Chat channel is not removed from UI when user is programmatically removed from channel using removeMembers

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-swiftui#40] opened 2022-04-04 06:40 UTC
## What did you do?
In our app, users are added and removed from admin panel which call the server to execute `addMembers` and `removeMembers` on different channels.

Use case:
Step 1: Keep the app open as all channels of user are visible
Step 2: Remove the user from a channel using `removeMembers` method call from server

## What did you expect to happen?
Expectation was that the chat screen would update and that particular channel will be removed from the chat list immediately.

## What happened instead?
The channel wasn't removed from the chat list and user was able to interact with that channel. Even switching app from background to foreground does not update the chat list. Also in this scenario, when app is brought from background to foreground then clicking on any channel in chat list would crash the app.

## GetStream Environment
**GetStream Chat version:*Using from master branch*
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:*14.8.1*
**Swift version:*Swift 5*
**Xcode version:*13.2.1*
**Device:*iPhone 11*

**Comment by martinmitrevski** [comment] 2022-04-04 07:34
Hey @JayMehta97,

Thanks for reporting this. We've started analysing the issue and as soon as we have an update, we'll post it here.

**Comment by JayMehta97** [comment] 2022-04-04 11:58
Hey @martinmitrevski ,

The channel gets removed immediately from the UI but if after that you bring the app from background to foreground then it is still crashing. Let me know if you need any other detail.

**Comment by martinmitrevski** [comment] 2022-04-04 12:44
Hey @JayMehta97, I can't reproduce this crash even on iOS 14 version. Maybe you can send the crash log you are getting, that might help figure out the nature of the crash.

**Comment by JayMehta97** [comment] 2022-04-04 13:01
Hey @martinmitrevski,

Sure, please find the screenshots attached from Xcode. Let me know if any other details are required.

![Screenshot 2022-04-04 at 6 30 11 PM](https://user-images.githubusercontent.com/12833091/161549216-af53ee63-21f3-43b7-b9c4-d6a21874d33a.png)

![Screenshot 2022-04-04 at 6 29 15 PM](https://user-images.githubusercontent.com/12833091/161549198-891e9b3e-87bc-47a5-ae08-dec4158bad4d.png)

**Comment by martinmitrevski** [comment] 2022-04-04 13:04
Yes, one more thing would be helpful @JayMehta97 - a snippet of how are you using the `ChatChannelListView` in its parent view. Might be some issue with some state recreated.

**Comment by martinmitrevski** [comment] 2022-04-04 13:22
Based on the second screenshot - it seems that when you go to the background, the `ChatChannelListView` is recreated, along with its ViewModel and the controller is out of sync, since syncronize is not called (thus the channel is nil). 

My assumption is that this happens even when you don't do this add/remove members call from the backend, but just go from background to foreground. Can you please check if that's the case?

**Comment by JayMehta97** [comment] 2022-04-04 13:44
Hi @martinmitrevski,

Here is a snippet of how we call our `CustomChatList` and I have also attached code file for CustomChatList as TXT:
```
struct ChatScreen: View {
  @EnvironmentObject var appSettings: AppSettings

  @ObservedObject private(set) var viewModel: ViewModel

  @State private var shouldShowChat = false

  private let cancelBag = CancelBag()

  var body: some View {
    if shouldShowChat {
        CustomChatList(
          viewFactory: CustomChatListFactory.shared,
          onChannelSelected: onChannelSelected
        )
        .onAppear {
          rootTabBarSettings.shouldHideBottomTabBar = false
        }
      }
    } else {
      // ....
    }
    .onAppear {
      viewModel.container.appState
        .updates(for: \.userDetails)
        .sink { userDetails in
          // Can change value of `shouldShowChat` here but in the crash 
              scenario the value doesn't get update and stays true
        }
        .store(in: cancelBag)
    }
  }
}
```
[CustomChatList.txt](https://github.com/GetStream/stream-chat-swiftui/files/8410189/CustomChatList.txt)

- And this is not happening if I just go from background to foreground.

Hope this helps, let me know if any other details are required.

**Comment by martinmitrevski** [comment] 2022-04-04 14:30
@JayMehta97 can you please check if the crash is still present with the latest changes on `main`?

**Comment by JayMehta97** [comment] 2022-04-04 14:39
@martinmitrevski 

I tried the same scenario with latest changes from main, when clicking on channel the app didn't crash but it showed a blank page with a loader instead of the message list screen (I have attached a screenshot of it). The loader keeps spinning indefinitely. But if press back from this loading screen and then again click on the same chat then it opens the message list screen with correct data.

![IMG_9133](https://user-images.githubusercontent.com/12833091/161568107-610d9e24-9601-4441-aaad-8cd405900a04.PNG)

**Comment by martinmitrevski** [comment] 2022-04-04 14:52
hey @JayMehta97, I think we're getting closer. May I ask you to try this branch `test-members-crash` before we merge it to `main`?

**Comment by JayMehta97** [comment] 2022-04-04 15:18
Hey @martinmitrevski , I tried branch `test-members-crash` but it is crashing with same log I had sent earlier.

**Comment by JayMehta97** [comment] 2022-04-04 16:03
Hey @martinmitrevski , it was SPM caching issue which didn't fetch latest `test-members-crash` code. I ran the same scenario with latest `test-members-crash` code, this time also it shows a loading screen and even clicking back and again on channel from chat list shows the same loading screen.

To answer your other questions:
- We are not using offline mode
- `shouldShowChat` is changed when user is removed from all chats but in my test cases for this scenario, user is always part of atleast 1 channel even after removal.
- We call an API when we enter foreground to check if user is removed from channels or not

**Comment by JayMehta97** [comment] 2022-04-06 07:44
Hey @martinmitrevski ,

As we discovered in our debug session that the app was calling `setup` stream multiple times which caused this issue, adding a check in the setup method to not intialize again if its not `nil` has solved this issue. Thanks for the help.

**Comment by martinmitrevski** [comment] 2022-04-06 13:49
Thanks @JayMehta97, I will close this one and we can track the relevant issues about adding members in https://github.com/GetStream/stream-chat-swiftui/issues/41.

**Closed by martinmitrevski** 2022-04-06 13:49 UTC
