### ISSUE TITLE
messageCurrentUserTextColor not working in 4.50

### ISSUE THREAD

**Issue by combef-luna** [GetStream/stream-chat-swiftui#453] opened 2024-03-13 16:42 UTC
## What did you do?
I instantiate `StreamChat` with an `Appearance` with `ColorPalette` using `messageCurrentUserTextColor` as `UIColor.white`.
I updated the library to 4.50.0 (was 4.49.0 before)

## What did you expect to happen?
The texts in the current user messages are black.

## What happened instead?
They should be white

## GetStream Environment
**GetStream Chat version:** 4.50.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.4
**Swift version:** 5.10
**Xcode version:** 15.3
**Device:** iPhone 15 pro

**Comment by martinmitrevski** [comment] 2024-03-13 16:56
Hi @combef-luna,

Thanks for reporting. I transferred this to the SwiftUI repo, since the issue is there. We have created a PR to address this: https://github.com/GetStream/stream-chat-swiftui/pull/452. 

We will provide a patch release soon as well.

Best, Martin

**Comment by martinmitrevski** [comment] 2024-03-14 00:13
The fix is now available in 4.50.1, thanks again for reporting.

**Closed by martinmitrevski** 2024-03-14 00:13 UTC
