### ISSUE TITLE
Photo viewers do not size/position photos correctly anymore after you swipe left and right

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#32] opened 2022-02-12 06:11 UTC
## What did you do?

https://user-images.githubusercontent.com/97132583/153699430-7a1cc01e-12d5-46e4-9032-39971ec2ad48.mp4

## What did you expect to happen?
When I send 2 screenshots (taken on iPhone 13 Pro) and opened them in photo viewer .... the photos are initially correctly sized and position (aspect-ratio-fit and centered). Then I swipe left and right to view both photos ... watch the video, the photos are suddenly incorrectly sized and incorrectly positioned.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat 4.10.0, StreamChatSwiftUI 4.9.0
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

**Comment by martinmitrevski** [comment] 2022-02-14 07:21
Hi @linhewinner, 

Thanks for reporting this. We will analyse the issue internally and provide a fix soon.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-02-14 09:25
The issue is fixed on `main` and it will be included in the next release on Wednesday.

**Closed by martinmitrevski** 2022-02-14 09:25 UTC
