### ISSUE TITLE
Memory does not deallocate

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#106] opened 2022-06-13 05:15 UTC
## What did you do?
- look into some chat messages screen

## What did you expect to happen?
- memory should deallocate automatically

## What happened instead?
- memory does not deallocate even when pop back to the channel list screen

## GetStream Environment
**GetStream Chat version:** 4.16.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 15.2
**Swift version:** 5
**Xcode version:** 13.2
**Device:** Iphone 13

## Additional context

https://user-images.githubusercontent.com/47667077/173284249-0d545093-ac76-4890-8976-6791b6441226.mp4

**Comment by ajay-simform** [comment] 2022-06-16 10:01
Hi @adolfogarza , Any update on this?

**Comment by adolfogarza** [comment] 2022-06-16 13:59
Hi @ajay-simform,

The issue is currently being explored by our team. We'll be sure to respond and provide a fix once the exact root cause is known.

Best Regards,

**Comment by martinmitrevski** [comment] 2022-06-19 11:22
Hey @ajay-simform, 

Thanks for bringing up this issue. There's a fix already available on `main` and it will be included in the next release. In any case, even with the increased memory and the previous state, there won't be crashes, since we always clear the memory cache on memory warnings.

Here's a bit more context: 
- We cache the images in memory, even after the chat is dismissed (for faster future loading).
- We understand that the increased memory usage might be concerning for our customers, so now instead of keeping the whole cache, we are trimming it to a config value of 100 MB when the chat is dismissed.
- You can clear the whole memory cache on chat dismiss by setting `cacheSizeOnChatDismiss` to 0 or smaller value (e.g. 1024 * 1024 * 50 for 50 MB) in the `MessageListConfig`. Setting `cacheSizeOnChatDismiss` to 0 will clear all images from memory when the chat screen is dismissed, which will bring the memory to its initial state.

Hope this solves the issue for you. Let us know if you have any other questions.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-06-24 07:28
hey @ajay-simform, 

Any feedback about our fix? If not, we can close this issue.

Best,
Martin

**Closed** 2022-06-27 06:49 UTC
