### ISSUE TITLE
Slide-in animation of attachment buttons showing when they should not, in channel screen

### ISSUE THREAD

**Issue by sslash** [GetStream/stream-chat-swiftui#464] opened 2024-03-26 10:58 UTC
## What did you do?
Open the `ChatChannelView` (not a custom one, I'm using the default from this library) > seeing the attachment buttons sliding in behind the input

## What did you expect to happen?
Not see the attachments

## What happened instead?
Seeing the attachments + a spinner slide in behind the input

## GetStream Environment
**GetStream Chat version:** 4.49.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.0.0
**Swift version:**  5
**Xcode version:** 15.0.1
**Device:** iPhone 15 pro

## Additional context
Here's how it looks with slow animations enabled:

https://github.com/GetStream/stream-chat-swiftui/assets/1174520/ab7aa57f-c141-4ca0-9ac7-efaf1c407322

**Comment by martinmitrevski** [comment] 2024-03-26 14:44
Hey @sslash,

This seems like an animation inherited from the parent view that holds our channel view. Are you doing any specific animation higher up the hierarchy?

**Comment by sslash** [comment] 2024-03-27 06:24
I'd think it was due to a `withAnimation` call up the hierarchy on our side, but it doesn't seem like we are doing that. 

It doesn't help adding a 
```
.transaction { transaction in
    transaction.animation = nil
}
```
around `ChatChannelView` either.

No worries if it's not easily reproducible on your side, I'm happy to add a short-loading overlay, which hides the problem.

**Comment by martinmitrevski** [comment] 2024-03-28 11:27
Yes, we were not able to reproduce this internally. Closing it for now, if you have some reproduction steps / sample code, please share it and we will look again.

**Closed by martinmitrevski** 2024-03-28 11:27 UTC
