### ISSUE TITLE
Navigation bar grows unexpectedly on iPadOS

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swiftui#149] opened 2022-07-22 18:07 UTC
## What did you do?

Scrolled to the bottom of a message list view.

## What did you expect to happen?

I expected the navigation bar / toolbar to remain in the same style it was in when the message list view was scrolled up higher.

## What happened instead?

The toolbar animates larger in height, but is not filled with any content to justify the growth. The style change is expected, but the growth of it is unexpected.

## GetStream Environment
**GetStream Chat frameworks:** StreamChat (4.18.0), StreamChatSwiftUI (`main`)
**iOS version:** 15.5
**Swift version:** latest
**Xcode version:** Version 13.4.1 (13F100)
**Device:** iPad Pro (12.9-inch) (5th generation)

## Additional context

This issue only happens on iPad and does not happen on iPhone.

Issue is demonstrated about halfway through this video:
https://user-images.githubusercontent.com/144283/180496810-9b2dffb7-7bd2-44d9-b056-02e03d23411e.MP4

I know from previous discussions that platforms other than iOS are not officially supported. I’m very grateful that everything works as well as it does on iPadOS. This kind of issue is admittedly not a very big deal, and I’m sure you have a lot to deal with, but figured I’d create the issue anyway in case it’s a quick fix. If not, no worries!

**Comment by martinmitrevski** [comment] 2022-07-22 19:24
Hey @moubry,

Thanks for reporting this. We will have a look for sure. 

When we have an update, we will report back.

Best,
Martin

**Comment by martinmitrevski** [comment] 2022-07-25 12:11
Hey @moubry,

The issue is now fixed and available on our `main` branch. It will go into our next release.

Best,
Martin

**Closed by martinmitrevski** 2022-07-25 12:11 UTC
